name: expense_tracker_bloc_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.0.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  uuid: ^4.5.1
  
  firebase_core: ^3.13.1

  expense_repository:
    path: packages/expense_repository



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
