name: expense_repository
description: The Repo that handles expenses
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies: 
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true